{{- if .Values.mealPlannerService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: meal-planner-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "macromind.labels" . | nindent 4 }}
    app: meal-planner-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: meal-planner-service
{{- end }}

