{{- if .Values.nutritionAIService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nutrition-ai-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "macromind.labels" . | nindent 4 }}
    app: nutrition-ai-service
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: nutrition-ai-service
{{- end }}

